### ISSUE TITLE
Incomplete and missing works; example: At the Mountains of Madness.

### ISSUE THREAD

**Issue by mknepper** [standardebooks/h-p-lovecraft_short-fiction#9]
I was going through Short Fiction by H.P. Lovecraft from Standard Books, and noticed that several pieces of Lovecraft's work are missing.

A few that immediately jumped out are:

1. At the Mountains of Madness
2. Herbert West—Reanimator
3. The Shadow Over Innsmouth
4. From Beyond
5. The Dream-Quest of Unknown Kadath

I'm sure there are others, but I thought I'd point out that there are several famous Lovecraft pieces missing. These works were either adapted to other forms of media or referenced in popular culture to some degree. It might be important to include them, especially these five I've listed. 

There are likely more not included, but I am currently unable to sort them all.

**Comment by acabal** [comment]
Lovecraft has an extremely complex publication history and many of his works are not yet provably in the US public domain. Thus, we can't include them. This collection only includes his US-PD work, as Standard Ebooks only produced US-PD ebooks. This is also why versions of the stories in this collection may differ from versions published or edited later.

Project Gutenberg is our guide for what is or isn't public domain. If the story isn't posted there, then we can't use it.
